Update patch set 12
Patch Set 12:

Have reoredred this commit as the autotools generates the config.h which conflicts with the https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-time-manager/+/41093/7/types.hpp

=============================================================================
FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -Werror -std=c++17 -O2 -g -MD -MQ phosphor-time-manager.p/main.cpp.o -MF phosphor-time-manager.p/main.cpp.o.d -o phosphor-time-manager.p/main.cpp.o -c ../main.cpp
In file included from ../epoch_base.hpp:3,
                 from ../bmc_epoch.hpp:3,
                 from ../main.cpp:3:
../config.h:53:21: error: expected unqualified-id before string constant
   53 | #define OBJPATH_BMC "/xyz/openbmc_project/time/bmc"
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../types.hpp:8:16: note: in expansion of macro ‘OBJPATH_BMC’
    8 | constexpr auto OBJPATH_BMC = "/xyz/openbmc_project/time/bmc";
      |                ^~~~~~~~~~~
../config.h:5:17: error: expected unqualified-id before string constant
    5 | #define BUSNAME "xyz.openbmc_project.Time.Manager"
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

========================================================================================

Patch-set: 12