DO-NOT-MERGE: Add -flto flag
Add -flto to see if CI pass the build or not;
CI says undefined reference to
`phosphor::time::Manager::PROPERTY_TIME_MODE'.

Change to use C++17 which probably fixes the above issue

Change-Id: I11c5c6c2b586addc0737d5b4d7d53a228d012ef4
Signed-off-by: Lei YU <mine260309@gmail.com>